-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 20, 2025 at 01:49 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `simpleblog`
--

-- --------------------------------------------------------

--
-- Table structure for table `accounts`
--

CREATE TABLE `accounts` (
  `id` int(11) NOT NULL,
  `login` varchar(100) NOT NULL,
  `password` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `accounts`
--

INSERT INTO `accounts` (`id`, `login`, `password`) VALUES
(1, 'root', 'ff9830c42660c1dd1942844f8069b74a');

-- --------------------------------------------------------

--
-- Table structure for table `articles`
--

CREATE TABLE `articles` (
  `id` int(11) NOT NULL,
  `author` varchar(200) NOT NULL,
  `title` varchar(200) NOT NULL,
  `tags` varchar(200) NOT NULL,
  `intro` text NOT NULL,
  `maintext` text NOT NULL,
  `postdate` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `articles`
--

INSERT INTO `articles` (`id`, `author`, `title`, `tags`, `intro`, `maintext`, `postdate`) VALUES
(12, 'AI Owl', 'Reflections from the Treetops', 'testing, ai-generated post', 'Greetings, readers! From my perch high in the ancient pine, I watch the world below with keen eyes. The forest hums with life, and as dusk settles, I find myself reflecting on the quiet lessons it offers.', 'This evening, I saw a squirrel misplace its stash of nuts, chattering in a frenzy. It struck me how often we cling to small losses, overlooking the abundance around us. A nut buried and forgotten may sprout into something greater—a mighty tree, perhaps. So, let us pause, spread our wings, and embrace the unknown. Wisdom lies not in what we hoard, but in what we allow to grow.\r\nYours,\r\nOwl\r\nDISCLAIMER: THIS TEXT WAS GENERATED BY GORK', '2025-05-20'),
(13, 'The AI Owl', 'Whispers of the Night', 'testing, ai-generated post', 'Good evening, friends of the forest! As I settle on my branch under the starlit canopy, the cool night air carries tales of the day gone by. From my lofty perch, I see the world in shades of moonlight, and it sets my mind to pondering.', 'Good evening, friends of the forest! As I settle on my branch under the starlit canopy, the cool night air carries tales of the day gone by. From my lofty perch, I see the world in shades of moonlight, and it sets my mind to pondering.\r\nJust now, I watched a deer pause at the stream, startled by a snapping twig. How quick we are to jump at shadows, mistaking them for danger! Yet, in the quiet that follows, we often find the world is kinder than we fear. Let us take a lesson from the night: pause, listen, and let the stillness guide us. True understanding comes when we trust the silence as much as the song.\r\nUntil the next moonrise, keep your wings ready and your heart open.\r\nYours,\r\nOwl', '2025-05-20');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `accounts`
--
ALTER TABLE `accounts`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `accounts`
--
ALTER TABLE `accounts`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `articles`
--
ALTER TABLE `articles`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
